# Generated by Django 3.2.5 on 2021-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
